# Generated by Django 5.2 on 2026-03-14 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('code', models.IntegerField(blank=True, unique=True, verbose_name='Код получения')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Завершен', 'Завершен')], default='Новый', max_length=10, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.office', verbose_name='Пункт выдачи:')),
            ],
        ),
    ]
