# Generated by Django 5.2 on 2026-03-14 15:15

import concurrency.fields
import django.core.validators
import django.db.models.deletion
import django_resized.forms
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120, verbose_name='Артикул')),
                ('product_name', models.CharField(choices=[('Ботинки', 'Ботинки'), ('Кеды', 'Кеды'), ('Кроссовки', 'Кроссовки'), ('Полуботинки', 'Полуботинки'), ('Сапоги', 'Сапоги'), ('Тапочки', 'Тапочки'), ('Туфли', 'Туфли')], max_length=120, verbose_name='Наименование товара')),
                ('unit_of_measurement', models.CharField(choices=[('шт.', 'шт.')], max_length=20, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('product_category', models.CharField(choices=[('Женская обувь', 'Женская обувь'), ('Мужская обувь', 'Мужская обувь')], max_length=20, verbose_name='Категория')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Скидка')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, default='picture.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 200], upload_to='', verbose_name='Изображение')),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manufacturer', verbose_name='Производитель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
